[package]
name = "modexp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "modexp"
path = "src/lib.rs"

[[bin]]
name = "modexp"
path = "src/main.rs"

[dependencies]
strum = "0.24.1"
strum_macros = "0.24.1"
halo2_proofs = { git = "https://github.com/junyu0312/halo2", branch = "gpu", default-features = true }
halo2ecc-s = { git = "https://github.com/lanbones/halo2ecc-s.git", branch = "bisect-lookup" }
num-bigint = { version = "0.4", features = ["rand"] }
poseidon = { git = "https://github.com/lanbones/poseidon" }
rand = "0.8"
ark-std = { version = "0.3.0", features = ["print-trace"] }
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"
clap = { version = "3.2.22", features = ["derive", "cargo"] }
subtle = "2.4"
lazy_static = "1.4.0"
hex = "0.4"
mongodb = { version = "2.5.0", default-features = false, features = ["async-std-runtime"] }
ripemd = "0.1.3"
futures = "0.3.28"